version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - auto_answer_network

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.development
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - auto_answer_network

volumes:
  db_data:

networks:
  auto_answer_network:
    external: true